# Generated by Django 4.1.3 on 2022-11-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona',
        ),
    ]
