# Generated by Django 4.1.3 on 2022-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=20),
        ),
    ]
