# Generated by Django 4.1.3 on 2022-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
